language: node_js
node_js:
  - "8"
  - "10"
  - "12"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn lint
  - yarn test
after_success:
  - yarn coverage
